
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "Fira Code"
style = "Medium"

[window]
decorations = "none"

[window.dimensions]
columns = 140
lines = 40

[window.position]
x = 510
y = 280

[general]
import = ["/home/dkxy/.config/alacritty/alacritty-theme/themes/github_dark.toml"]
